install:
  - cinst -y jdk8 -version 8.0.92
  - cinst -y ant -ignoreDependencies
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_92
  - set PATH=%JAVA_HOME%\bin;%PATH%
  - set BUCK_EXTRA_JAVA_ARGS=-Djna.nosys=true
  - python --version
  - java -version
  - ant -version


build_script:
  - ant clean default
  - bin\\buck build buck

test_script:
  - bin\\buck test --config go.root=/nonexistent --all --test-selectors=@windows_failures.txt --test-selectors=@windows_cxx_support.txt --explain-test-selectors

artifacts:
  - path: buck-out\gen\programs\buck.pex

